### ISSUE TITLE
_ros2_daemon and ros2 param commands

### ISSUE THREAD

**Issue by vatsan007** [ros2/ros2cli#668] opened 2021-10-06 10:33 UTC
## Bug report

**Required Info:**

- Operating System:
  -  Debian 9 (Stretch) 
- Installation type:
  - Foxy -- Built from source
- Version or commit hash:
  - 
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - ros2cli, _ros2_daemon

#### Steps to reproduce issue
I've some ros2 nodes which are being run as a system user. These nodes work fine and all ros2cli commands like ros2 node list, 
 ros2 param list/get -- all work fine when run as a system user.

However, when the ros2cli commands are run as root, it is observed that _ros2_daemon is not responding properly and the CPU usage of _ros2_daemon increases to 95% and remains there. It isn't recovering. Also, all the ros2 param commands fail - with the error "Node not found".

Is this behaviour expected? Shouldn't ros2cli commands work fine even when run under root?

The only way to recover from this scenario is restart all the nodes and restart of ros2 daemon using ros2 daemon stop/start commands as system user.

**Comment by clalancette** [comment] 2021-10-06 12:32
In theory, that combination should all work.  But we don't test on Debian Stretch, and we don't test as root, so you are kind of in uncharted territory here.  That said, if you find the cause of the problem we'd be happy to review fixes for it.

**Comment by vatsan007** [comment] 2021-10-19 03:26
Thanks for the reply. Disabling shared memory feature as mentioned in eProsima/Fast-DDS#1750 - did work as I mentioned above. The high CPU usage also disappeared with the above change. 

I've one more query -- What will the after-effect of the above change? Will it change the underlying transport to UDP transport for even messages going out on ROS2 channels between 2 nodes?

**Comment by fujitatomoya** [comment] 2021-10-19 03:39
> Will it change the underlying transport to UDP transport for even messages going out on ROS2 channels between 2 nodes?

shared memory is only effective between endpoints in localhost. so after this setting, you also will UDP transport instead of shared memory. about network connection, UDP is default setting. (i may be missing something, @IkerLuengo friendly ping.)

**Comment by clalancette** [comment] 2022-02-03 20:38
I think the original issue was fixed/worked around, so I'm going to close this out.  If there is still a problem here, please feel free to reopen.

**Closed by clalancette** 2022-02-03 20:38 UTC
Labels: backlog
