### ISSUE TITLE
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/ros2cli#358] opened 2019-10-10 02:41 UTC
## Bug report

the following message comes up every single time to issue ros2cli commands.

```
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'
```

**Required Info:**

- Operating System:
  - Ubuntu18.04
- Installation type:
  - source build
- Version or commit hash:
  - ros2.repo master
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

just start node or issue ros2cli command,

```
root@6cc2c62d0dd0:~/ros2_colcon_ws# ros2 run demo_nodes_cpp talker
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'
[INFO] [talker]: Publishing: 'Hello World: 1'
[INFO] [talker]: Publishing: 'Hello World: 2'
[INFO] [talker]: Publishing: 'Hello World: 3'
```

```
root@6cc2c62d0dd0:~/ros2_colcon_ws# ros2 node info /talker
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'
/talker
  Subscribers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
  Publishers:
    /chatter: std_msgs/msg/String
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /rosout: rcl_interfaces/msg/Log
  Services:
    /talker/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /talker/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /talker/get_parameters: rcl_interfaces/srv/GetParameters
    /talker/list_parameters: rcl_interfaces/srv/ListParameters
    /talker/set_parameters: rcl_interfaces/srv/SetParameters
    /talker/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Actions Servers:


```

#### Expected behavior

No failure message comes up.

#### Actual behavior

the following failure message comes up.
```
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'
```

#### Additional information

N.A

## Feature request

N.A

#### Feature description

N.A

#### Implementation considerations

N.A

**Comment by dirk-thomas** [comment] 2019-10-10 03:02
Duplicate of ros2/ros2cli#352. Please make sure that you are using the latest version of this repository.

**Closed by dirk-thomas** 2019-10-10 03:02 UTC
Labels: duplicate
