### ISSUE TITLE
Can't pass args to an executable

### ISSUE THREAD

**Issue by allenh1** [ros2/ros2cli#28] opened 2017-06-27 23:03 UTC
```
allenh1@machina:~/ros2_ws$ ros2 run ros1_bridge dynamic_bridge --show-introspective
usage: ros2 [-h] Call `ros2 <command> -h` for more detailed usage. ...
ros2: error: unrecognized arguments: --show-introspective
```

I have argcomplete installed, and working, but I cannot complete a binary, nor can I pass any arguments to the executable.

**Comment by mikaelarguedas** [comment] 2017-06-27 23:06
please look at the help message of ros2 run
```
  package_name     Name of the ROS package
  executable_name  Name of the executable
  argv             Pass arbitrary arguments to the executable (use '--' before
                   these arguments to ensure they are not handle by this
                   command
```
duplicate of https://github.com/ros2/ros2cli/issues/16

**Closed by mikaelarguedas** 2017-06-27 23:06 UTC
