### ISSUE TITLE
Broken ROS2 GetParameters service response if any of the parameter is declared but not defined

### ISSUE THREAD

**Issue by EwingKang** [ros2/ros2cli#924] opened 2024-08-22 03:00 UTC
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 22.04
- Installation type:
  -  binaries
- Version or commit hash:
  -  IRON
- DDS implementation:
  -  N/A
- Client library (if applicable):
  -  ros cli (ros service)

Empty/ broken GetParameters service response if any of the parameter is declared but not defined.

#### Steps to reproduce issue
```c++ 
//my_node.cpp....

// declare parameters with default value
this->declare_parameter("alpha", 0.3, desc("alpha"));
this->declare_parameter("beta", 5.0, desc("beta"));

// This parameter is declared without default value causes problem
this->declare_parameter("help", rclcpp::PARAMETER_BOOL);

//...
```
Call the `GetParameters` service returns fine: 
```bash
ros2 service call /my_node/get_parameters rcl_interfaces/srv/GetParameters "{names: [alpha, beta]}"

# Response
requester: making request: rcl_interfaces.srv.GetParameters_Request(names=['alpha', 'beta'])

response:
rcl_interfaces.srv.GetParameters_Response(values=[rcl_interfaces.msg.ParameterValue(type=3, bool_value=False, integer_value=0, double_value=0.3, string_value='', byte_array_value=[], bool_array_value=[], integer_array_value=[], double_array_value=[], string_array_value=[]), rcl_interfaces.msg.ParameterValue(type=3, bool_value=False, integer_value=0, double_value=5.0, string_value='', byte_array_value=[], bool_array_value=[], integer_array_value=[], double_array_value=[], string_array_value=[])])
```

However, if any one of the requested parameter has no default parameter, the entire service call returns broken entry
```bash
ros2 service call /my_node/get_parameters rcl_interfaces/srv/GetParameters "{names: [alpha, beta, help]}"

# Response
waiting for service to become available...
requester: making request: rcl_interfaces.srv.GetParameters_Request(names=['alpha', 'beta', 'help'])

response:
rcl_interfaces.srv.GetParameters_Response(values=[])
```

#### Expected behavior
For parameters with default value, return normally; for parameters without default value, some sort of flag to mark the situation

#### Actual behavior
As described above

#### Additional information
I believe this is related to https://github.com/ros-visualization/rqt_reconfigure/issues/142

**Comment by EwingKang** [comment] 2024-08-22 04:20
This might be related to: https://github.com/ros2/rclcpp/issues/2512

**Comment by fujitatomoya** [comment] 2024-08-22 04:39
@EwingKang thanks for posting issue. a couple of things i want to confirm.

> Call the DescribeParameters service returns fine:

it looks like you are calling `GetParameters` service, is this typo?

> ros2 service call /my_node/get_parameters rcl_interfaces/srv/GetParameters "{names: [alpha, beta]}"

where is this `beta` defined? is this supposed to be `lamda`?

can you check the issue description? i just want to be sure the issue description.

**Comment by EwingKang** [comment] 2024-08-22 06:07
@fujitatomoya I'm terribly embarrassed by the mistake! I fixed the description.
Thanks for catching the error! It is exactly like what you imagine. Things were lost during copy and paste.
Please let me know if there's any confusion, thanks!

**Comment by fujitatomoya** [comment] 2024-08-22 16:11
@EwingKang thanks for checking this.

as you mentioned, this is similar with https://github.com/ros2/rclcpp/issues/2512 which explains specifically on `GetParameterTypes` but the point is inconsistent behavior against documentation.

Here it  complains about `GetParameter`, the behavior also does not match with https://docs.ros2.org/galactic/api/rcl_interfaces/srv/GetParameterTypes.html.

**Comment by fujitatomoya** [comment] 2024-08-22 16:12
Note: I think this issue can move to `rclcpp` repository since the service server is implemented in `rclcpp` that responds the service request via ros2cli.

**Comment by sloretz** [comment] 2024-08-29 20:36
Thank you for the report! Closing as a duplicate of https://github.com/ros2/rclcpp/issues/2512 🧇

**Closed by sloretz** 2024-08-29 20:36 UTC
Labels: bug
